{% set version = "3.0.0" %}

package:
  name: triqs_cthyb
  version: {{ version }}

source:
  url: https://github.com/TRIQS/cthyb/releases/download/{{ version }}/cthyb-{{ version }}.tar.gz
  sha256: 64970bfc73f5be819a87044411b4cc9e1f7996d122158c5c011046b7e1aec4e5

build:
  number: 1
  skip: True  # [win or py<30]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - triqs {{ '.'.join(version.split('.')[:2]) }}
    - boost-cpp
    - nfft
    - hdf5
    - {{ mpi }}
    - libblas
    - liblapack
    - python
  run:
    - {{ pin_compatible("triqs", max_pin="x.x") }}
    - nfft
    - hdf5
    - {{ mpi }}
    - libblas
    - liblapack
    - python

test:
  commands:
    - export OMPI_MCA_btl=self,tcp
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - export mpiexec="mpiexec --allow-run-as-root"
    - python -c "import triqs_cthyb"

about:
  home: https://triqs.github.io/cthyb
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'A fast and generic hybridization-expansion impurity solver'

extra:
  recipe-maintainers:
    - wentzell
    - pgunn
