{% set version = "3.2.1" %}

package:
  name: triqs_cthyb
  version: {{ version }}

source:
  url: https://github.com/TRIQS/cthyb/releases/download/{{ version }}/cthyb-{{ version }}.tar.gz
  sha256: 6f4cd36efcd19b0f1efbed2c9aa6d2640ef84f8fcf7b97675af8d54cdc327c9f

build:
  number: 2
  skip: true  # [win or py<30]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - wget                                   # [target_platform == 'osx-arm64']
    - libtool                                # [target_platform == 'osx-arm64']
    - autoconf                               # [target_platform == 'osx-arm64']
    - automake                               # [target_platform == 'osx-arm64']
    - llvm-openmp                            # [target_platform == 'osx-arm64']
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ mpi }}                              # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - triqs {{ '.'.join(version.split('.')[:2]) }}
    - libboost-headers
    - nfft                                   # [target_platform != 'osx-arm64']
    - fftw                                   # [target_platform == 'osx-arm64']
    - hdf5
    - {{ mpi }}
    - libblas
    - liblapack
    - numpy
    - python
  run:
    - {{ pin_compatible("triqs", max_pin="x.x") }}
    - nfft                                   # [target_platform != 'osx-arm64']
    - fftw                                   # [target_platform == 'osx-arm64']
    - hdf5
    - {{ mpi }}
    - libblas
    - liblapack
    - {{ pin_compatible("numpy") }}
    - python

test:
  commands:
    - export OMPI_MCA_btl=self,tcp
    - export OMPI_MCA_plm=isolated
    - export OMPI_MCA_rmaps_base_oversubscribe=yes
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none
    - export mpiexec="mpiexec --allow-run-as-root"
    - python -c "import triqs_cthyb"

about:
  home: https://triqs.github.io/cthyb
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: A fast and generic hybridization-expansion impurity solver

extra:
  recipe-maintainers:
    - wentzell
    - pgunn
    - thoemi09
